"""add complaint workflow tables

Revision ID: f0ec376ae4d3
Revises: 897c2c62eb4b
Create Date: 2026-10-04 02:19:30.379971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ec376ae4d3'
down_revision: Union[str, Sequence[str], None] = '897c2c62eb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_counters',
    sa.Column('year', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year', name=op.f('pk_id_counters'))
    )
    op.create_table('tat_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=12), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('tat_hours', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IS NULL OR category IN ('Hostel', 'Exam', 'Academic / Department', 'Infrastructure and facilities', 'Safety and welfare', 'Administrative / Fees', 'Library / Transport', 'Other')", name=op.f('ck_tat_rules_category_valid')),
    sa.CheckConstraint("priority IS NULL OR priority IN ('Low', 'Medium', 'High', 'Critical')", name=op.f('ck_tat_rules_priority_valid')),
    sa.CheckConstraint("stage IN ('REVIEW', 'RESOLUTION')", name=op.f('ck_tat_rules_stage_valid')),
    sa.CheckConstraint('escalation_level IS NULL OR escalation_level >= 1', name=op.f('ck_tat_rules_level_positive')),
    sa.CheckConstraint('tat_hours > 0', name=op.f('ck_tat_rules_hours_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tat_rules'))
    )
    op.create_table('escalation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=32), nullable=False),
    sa.Column('target_authority_level', sa.Integer(), nullable=False),
    sa.Column('target_scope', sa.String(length=32), nullable=False),
    sa.Column('target_department_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(target_scope = 'FIXED_DEPARTMENT' AND target_department_id IS NOT NULL) OR (target_scope <> 'FIXED_DEPARTMENT' AND target_department_id IS NULL)", name=op.f('ck_escalation_rules_department_matches_scope')),
    sa.CheckConstraint("category IS NULL OR category IN ('Hostel', 'Exam', 'Academic / Department', 'Infrastructure and facilities', 'Safety and welfare', 'Administrative / Fees', 'Library / Transport', 'Other')", name=op.f('ck_escalation_rules_category_valid')),
    sa.CheckConstraint("target_role IN ('department_authority', 'higher_authority')", name=op.f('ck_escalation_rules_target_role_valid')),
    sa.CheckConstraint("target_scope IN ('COMPLAINANT_DEPARTMENT', 'FIXED_DEPARTMENT', 'INSTITUTION')", name=op.f('ck_escalation_rules_target_scope_valid')),
    sa.CheckConstraint('escalation_level >= 1', name=op.f('ck_escalation_rules_level_positive')),
    sa.CheckConstraint('target_authority_level >= 1', name=op.f('ck_escalation_rules_authority_level_positive')),
    sa.ForeignKeyConstraint(['target_department_id'], ['departments.id'], name=op.f('fk_escalation_rules_target_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_rules'))
    )
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_code', sa.String(length=20), nullable=False),
    sa.Column('complainant_id', sa.Integer(), nullable=False),
    sa.Column('complainant_role', sa.String(length=32), nullable=False),
    sa.Column('complainant_department_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('decision_source', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('handling_department_id', sa.Integer(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('breached_at_top', sa.Boolean(), nullable=False),
    sa.Column('tat_stage', sa.String(length=12), nullable=False),
    sa.Column('tat_rule_id', sa.Integer(), nullable=False),
    sa.Column('tat_hours', sa.Float(), nullable=False),
    sa.Column('stage_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status IN ('RESOLVED', 'CLOSED') AND resolved_at IS NOT NULL) OR (status NOT IN ('RESOLVED', 'CLOSED') AND resolved_at IS NULL)", name=op.f('ck_complaints_resolved_at_matches_status')),
    sa.CheckConstraint("category IN ('Hostel', 'Exam', 'Academic / Department', 'Infrastructure and facilities', 'Safety and welfare', 'Administrative / Fees', 'Library / Transport', 'Other')", name=op.f('ck_complaints_category_valid')),
    sa.CheckConstraint("decision_source IN ('AI_PENDING_REVIEW', 'AI_AUTO', 'HUMAN_ACCEPTED', 'HUMAN_OVERRIDDEN')", name=op.f('ck_complaints_decision_source_valid')),
    sa.CheckConstraint("priority IN ('Low', 'Medium', 'High', 'Critical')", name=op.f('ck_complaints_priority_valid')),
    sa.CheckConstraint("status IN ('PENDING_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')", name=op.f('ck_complaints_status_valid')),
    sa.CheckConstraint("tat_stage IN ('REVIEW', 'RESOLUTION')", name=op.f('ck_complaints_tat_stage_valid')),
    sa.CheckConstraint('escalation_level >= 1', name=op.f('ck_complaints_escalation_level_positive')),
    sa.CheckConstraint('tat_hours > 0', name=op.f('ck_complaints_tat_hours_positive')),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_complaints_assigned_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complainant_department_id'], ['departments.id'], name=op.f('fk_complaints_complainant_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complainant_id'], ['users.id'], name=op.f('fk_complaints_complainant_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['handling_department_id'], ['departments.id'], name=op.f('fk_complaints_handling_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tat_rule_id'], ['tat_rules.id'], name=op.f('fk_complaints_tat_rule_id_tat_rules'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints')),
    sa.UniqueConstraint('complaint_code', name=op.f('uq_complaints_complaint_code'))
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_complainant_id'), ['complainant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_deadline_at'), ['deadline_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)

    op.create_table('ai_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('priority_confidence', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('threshold_source', sa.String(length=40), nullable=False),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('flag_reasons', sa.JSON(), nullable=False),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('Hostel', 'Exam', 'Academic / Department', 'Infrastructure and facilities', 'Safety and welfare', 'Administrative / Fees', 'Library / Transport', 'Other')", name=op.f('ck_ai_predictions_category_valid')),
    sa.CheckConstraint("priority IN ('Low', 'Medium', 'High', 'Critical')", name=op.f('ck_ai_predictions_priority_valid')),
    sa.CheckConstraint('category_confidence BETWEEN 0 AND 1', name=op.f('ck_ai_predictions_category_confidence_range')),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_ai_predictions_confidence_range')),
    sa.CheckConstraint('priority_confidence BETWEEN 0 AND 1', name=op.f('ck_ai_predictions_priority_confidence_range')),
    sa.CheckConstraint('threshold > 0 AND threshold <= 1', name=op.f('ck_ai_predictions_threshold_range')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_ai_predictions_complaint_id_complaints'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_predictions')),
    sa.UniqueConstraint('complaint_id', name=op.f('uq_ai_predictions_complaint_id'))
    )
    op.create_table('complaint_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_complaint_events_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_events_complaint_id_complaints'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_events'))
    )
    with op.batch_alter_table('complaint_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_events_complaint_id'), ['complaint_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_events_complaint_id'))

    op.drop_table('complaint_events')
    op.drop_table('ai_predictions')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_deadline_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_complainant_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_assigned_user_id'))

    op.drop_table('complaints')
    op.drop_table('escalation_rules')
    op.drop_table('tat_rules')
    op.drop_table('id_counters')
    # ### end Alembic commands ###
